application: we-tap
version: 1
runtime: python
api_version: 1

handlers:
-   url: /download
    static_dir: static/download
-   url: /images
    static_dir: static/images
-   url: /icons
    static_dir: static/icons
-   url: /js
    static_dir: js
-   url: /css
    static_dir: static/css
-   url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
-   url: /.*
    script: we-tap.py
